### ISSUE TITLE
Touch command variants (Debian vs BSD)

### ISSUE THREAD

**Issue by xave** [perfacilis/backup#4]
I think it would be ideal to note that this script is specialized for Debian. There are two `touch` commands out in the wild. The Debian version has a `-d` option. The BSD version does not. Therefore, the construction of the `starttime` variable is also specialized. I'm working on a version of this script for myself (macOS) and came up with this for the `starttime` binding:

```starttime=$(date +%C%y%m%d%H%M.%S)```

This gives an output for the BSD `touch`. And it would be called like this instead:

```touch -t "$STARTTIME" "$INCFILE"```

**Comment by royarisse** [comment]
It seems both BSD and Debian based variants of `touch` support the `-t` flag, so I'll add that.
Thanks for your research, It's a pleasure to see others using the script :)
