### ISSUE TITLE
Variants of `pidof` command (Debian vs BSD)

### ISSUE THREAD

**Issue by xave** [perfacilis/backup#5]
There are multiple variants of the `pidof` command. The one with the options in the script is for Debian. I had attempted to recreate the functionality with `ps`, `grep`, etc. But upon thinking about it, the goal of the `check_only_instance()` function is ultimately not to check and filter the process ids, but to ensure that the script only runs one instance at a time.

Therefore, I suggest that that function is removed and instead the flock(1) command is used at the top of the file, below the shell shebang. While I did have to install it on macOS, there is a portable version maintained by [discoteq](https://github.com/discoteq/flock). I used nix, but he also lists a Homebrew install method, so it should be generally accessible and portable.

## Usage 
Per the man page, the following command would be placed at the top of any script we only want a single instance of:

``` [ "${FLOCKER}" != "$0" ] && exec env FLOCKER="$0" flock -n "$0" "$0" "$@" || :```

What this does is to use the script itself as a lockfile. While `flock` has the lock set, no cron jobs could start another instance of the backup. 

## Testing

I did a simple test involving trying to invoke a simple script twice. The script prints out a string and also a random number:

# Test script:

```
echo "Check only instances."
echo "Random number is: $RANDOM."
```

# Test: 

The test involves invoking the following line with and without the above flock command at the top of the script.

```(trap 'kill 0' SIGINT; myscript & myscript)```

where `myscript` is the test script, and would eventually be the `backup` script from this repo. 

With the flock line included, we get the following output:

```
Check only instances
Random number is 46523.
```

Without the flock line, we get:

```
Check only instances.
Check only instances.
Random number is 26128.
Random number is 18439.
```

## Conclusion

I believe this is a portable method that works on Debian and BSD.

**Comment by royarisse** [comment]
I see the `flock` is available on Debian based systems by default, so I agree that it might be a viable option to replace `check_only_instance()`. I'll look into this as soon as I can. but feel free to create a pull request :)
