### ISSUE TITLE
Date syntax (Debian vs BSD)

### ISSUE THREAD

**Issue by xave** [perfacilis/backup#6]
In the `get_intervals_to_backup()` function, there is a call to set 

```LAST=$(date +%s -r "$INCFILE"```

This works on Debian, yet the BSD version wants the `+%s` portion at the end only, like so:

```LAST=$(date -r "$INCFILE" +%s)```

If the Debian version of this command is more permissive, then switching to the latter syntax would increase the portability.

**Comment by royarisse** [comment]
Thanks @xave, using your feedback I've just release version 0.9.3.

**Comment by royarisse** [comment]
Oops, I'm not paying attention, reopening the issue…

**Comment by royarisse** [comment]
Release version 0.10.1 with reordered date command.
Thanks for the suggestion @xave :+1:
