### ISSUE TITLE
Create backup-dir on target

### ISSUE THREAD

**Issue by mgoerens** [perfacilis/backup#7]
Hi, and first thanks a lot for sharing this script. I've been testing it over the week and I have a couple of remarks, for which I will open separate issues.

The path to the `backup-dir` in the script is `--backup-dir=/$PERIOD/$INC/$TARGET`. This will create for instance a `/hourly` folder on the host being backed up.

I prefer having those hourly, daily etc backups located on the target, next to the `current` folder. So I modified it as follow: `--backup-dir=$RSYNC_TARGET/$PERIOD/$INC/$TARGET`.

Personally that fits my use case better.

**Comment by mgoerens** [comment]
Indeed, I haven't used a rsync-server. I missed the nuance in the rsync documentation about `--backup-dir`. Following your explanations it makes more sense now.

Here is an example rsync command being run by the script as requested:

```
+ BACKUP_DIRS=($BACKUP_LOCAL_DIR /root/backup/src/dir1 /root/backup/src/dir2)
+ RSYNC_TARGET=/root/backup/target
+ rsync -trlqpz4 --delete --delete-excluded --prune-empty-dirs --exclude-from=./rsync.exclude --backup --backup-dir=/hourly/1/root_backup_backup-dir /root/backup/backup-dir/ /root/backup/target/current/root_backup_backup-dir
```

My use case ultimately is to backup data on an external HDD, so I will have something like `RSYNC_TARGET=/mnt/backup-hdd`

**Comment by royarisse** [comment]
Finally got around to research this issue, see version 0.10.2.
Had to forcefully prefix the `backup-dir` with `$RSYNC_TARGET` for local targets but coudn't do that for remote targets or everything would explode. Short story long: it's fixed :)

**Comment by mgoerens** [comment]
Thanks a bunch !
