### ISSUE TITLE
prepare_remote_dir creates empty tmp directory in current

### ISSUE THREAD

**Issue by mgoerens** [perfacilis/backup#8]
I couldn't grasp the need for calling `prepare_remote_dir "current"`.

From my understanding, it simply creates an empty tmp directory within the `current` folder. It does so for each period and for each folder being backed-up. After a couple of run, my `current` folder is flooded with those tmp directory.

It looks like you purposefully removed the trailing `/` after `$EMPTYDIR` in v0.8.2, and that you want an empty directory to be created. Could you explain the reasoning here ?

In any case, I think those empty tmp directory should be cleaned up.

**Comment by royarisse** [comment]
Note to self:
The `tmp.XXXXXX` dirs are created to ensure the remote path exists, it avoids rsync permission/no such path errors.
Research if the `--mkpath` option could be a working alternative to phase out `prepare_remote_dir()`.

**Comment by royarisse** [comment]
Finally found some time to get rid of pesky temp dir bug, thanks for your patience!
